/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.mysql.cj.x.protobuf.MysqlxCrud;
import java.awt.event.*;
import java.math.BigInteger;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Employee;
import model.Timekeeper;

/**
 *
 * @author Cuong
 */
public class View extends javax.swing.JFrame implements ActionListener{
    private static final long serialVersionUID = 1L;
    
    
    
    /**
     * Creates new form MainView
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmp = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField(new SimpleDateFormat("dd/mm/yyyy"));
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        labelID = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnCheck = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cbTKID = new javax.swing.JComboBox<>();
        cbInout = new javax.swing.JComboBox<>();
        cbEmpID = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTK = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "EMP_ID", "EMP_NAME", "EMP_NO", "HIRE_DATE", "JOB", "SALARY", "DEPT_ID", "MNG_ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmp);
        if (tblEmp.getColumnModel().getColumnCount() > 0) {
            tblEmp.getColumnModel().getColumn(0).setResizable(false);
            tblEmp.getColumnModel().getColumn(1).setResizable(false);
            tblEmp.getColumnModel().getColumn(2).setResizable(false);
            tblEmp.getColumnModel().getColumn(3).setResizable(false);
            tblEmp.getColumnModel().getColumn(4).setResizable(false);
            tblEmp.getColumnModel().getColumn(5).setResizable(false);
            tblEmp.getColumnModel().getColumn(6).setResizable(false);
            tblEmp.getColumnModel().getColumn(7).setResizable(false);
        }

        jButton2.setText("Sửa");

        jButton3.setText("Xóa");

        jLabel1.setText("EMP_NAME");

        jLabel2.setText("EMP_NO");

        jLabel3.setText("HIRE_DATE");

        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setText("EMP_ID");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel5.setText("JOB");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fresher IT", "Junior IT", "Senior IT", "IT Manager" }));

        jLabel6.setText("SALARY");

        jLabel7.setText("DEPT_ID");

        jLabel8.setText("MNG_ID");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jButton1.setText("Thêm");

        jButton4.setText("Cập nhật");
        jButton4.setEnabled(false);

        labelID.setText("ID");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)
                        .addComponent(jLabel8)))
                .addGap(52, 52, 52)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2)
                        .addComponent(jTextField6)
                        .addComponent(jTextField5)
                        .addComponent(jTextField4)
                        .addComponent(jFormattedTextField1)
                        .addComponent(jTextField3))
                    .addComponent(labelID))
                .addGap(74, 74, 74)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(labelID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1)))
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(50, 50, 50))
        );

        jTabbedPane1.addTab("Nhân viên", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Phòng ban", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lương", jPanel3);

        jLabel9.setText("TK_ID");

        jLabel10.setText("Date");

        jLabel11.setText("In/Out");

        jLabel12.setText("Emp_id");

        btnCheck.setText("Check in/out");

        jLabel13.setText("Date");

        cbTKID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TK1", "TK2", "TK3", "TK4" }));

        cbInout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In", "Out" }));

        tblTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "TK_ID", "Date", "In/out", "Emp_id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblTK);
        if (tblTK.getColumnModel().getColumnCount() > 0) {
            tblTK.getColumnModel().getColumn(0).setResizable(false);
            tblTK.getColumnModel().getColumn(1).setResizable(false);
            tblTK.getColumnModel().getColumn(2).setResizable(false);
            tblTK.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbEmpID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbTKID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13)
                            .addComponent(cbInout, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCheck)
                        .addGap(178, 178, 178))))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btnCheck)
                    .addComponent(cbTKID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbInout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thông tin đi làm", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void actionPerformed(ActionEvent e) {
    }
    //EmployeeViewListeners
    public void addEmpListener(ActionListener listener){
        jButton1.addActionListener(listener);
    }
    
    public void updateEmpListener(ActionListener listener){
        jButton4.addActionListener(listener);
    }
    
    public void editEmpListener(ActionListener listener){
        jButton2.addActionListener(listener);
    }
    
    public void deleteEmpListener(ActionListener listener){
        jButton3.addActionListener(listener);
    }
    
    //TimeKeeperViewListeners
    public void addTKListener(ActionListener listener){
        btnCheck.addActionListener(listener);
    }
    
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void showMessage(String l){
        JOptionPane.showMessageDialog(this, l);
    }
    
    //EmployeeViewFunctions
    public void showEditEmployee(){
        int row = tblEmp.getSelectedRow();           
        labelID.setText(tblEmp.getModel().getValueAt(row, 0).toString());
        jTextField2.setText(tblEmp.getModel().getValueAt(row, 1).toString());
        jTextField3.setText(tblEmp.getModel().getValueAt(row, 2).toString());
        jFormattedTextField1.setText(tblEmp.getModel().getValueAt(row, 3).toString());
       
        switch(tblEmp.getModel().getValueAt(row, 4).toString()){
            case "Fresher IT":
                jComboBox1.setSelectedIndex(0);
                break;
            case "Junior IT":
                jComboBox1.setSelectedIndex(1);
                break;
            case "Senior IT":
                jComboBox1.setSelectedIndex(2);
                break;
            case "IT Manager":
                jComboBox1.setSelectedIndex(4);
                break;
        }
        jTextField4.setText(tblEmp.getModel().getValueAt(row, 5).toString());
        jTextField5.setText(tblEmp.getModel().getValueAt(row, 6).toString());
        jTextField6.setText(tblEmp.getModel().getValueAt(row, 7).toString());  
        jButton4.setEnabled(true);
        jButton1.setEnabled(false);
    }
    
    public void showListEmployee(List<Employee> list){
        int size = list.size();
        
        Object [][] emps = new Object[size][8];
        for(int i=0; i<size; i++){
            emps[i][0] = list.get(i).getEmpId();
            emps[i][1] = list.get(i).getEmpName();
            emps[i][2] = list.get(i).getEmpNo();
            emps[i][3] = list.get(i).getHireDate();
            emps[i][4] = list.get(i).getJob();
            emps[i][5] = list.get(i).getSalary();
            emps[i][6] = list.get(i).getDeptId();
            emps[i][7] = list.get(i).getMngId();
        }
        tblEmp.setModel(new DefaultTableModel(emps, new String[] {"EMP_ID", "EMP_NAME", "EMP_NO", "HIRE_DATE", "JOB", "SALARY", "DEPT_ID", "MNG_ID"}));
    }
    
    public Employee getEmployee(){
        Employee emp = null;
        try{    
            String name = jTextField2.getText();
            String no = jTextField3.getText();
          
            SimpleDateFormat formatter = new SimpleDateFormat("dd/mm/yyyy");
            Date hireDate = formatter.parse(jFormattedTextField1.getText());
            int jobBox = jComboBox1.getSelectedIndex();
            String job = null;
            if(jobBox == 0){
                job = "Fresher IT";
            }
            if(jobBox == 1){
                job = "Junior IT";
            }
            if(jobBox == 2){
                job = "Senior IT";
            }
            if(jobBox == 3){
                job = "IT Manager";
            }
            float sal = Float.parseFloat(jTextField4.getText());
            int dept_id = Integer.parseInt(jTextField5.getText());
            java.math.BigInteger mng_id = BigInteger.valueOf(Long.parseLong(jTextField6.getText()));
            if( jTextField2.equals("") || jTextField3.equals("") || jTextField4.equals("") || jTextField5.equals("") || jTextField6.equals("")){
                showMessage("Khong duoc bo trong");
            } else if( sal <= 0 ||dept_id <=0 ){
                showMessage("Khong nhap so am");
            } else {               
                emp = new Employee(name, no, hireDate, null, job, sal,dept_id, mng_id);              
            }
        }catch(Exception e){
            showMessage("Nhap loi" + e);
        }
        return emp;
    }
    
    public Employee getUpdatedEmployee(){
        Employee emp = null;
        try{
            
            
            int id = Integer.parseInt(labelID.getText());
            String name = jTextField2.getText();
            String no = jTextField3.getText();
          
            SimpleDateFormat formatter = new SimpleDateFormat("dd/mm/yyyy");
            Date hireDate = formatter.parse(jFormattedTextField1.getText());
            int jobBox = jComboBox1.getSelectedIndex();
            String job = null;
            if(jobBox == 0){
                job = "Fresher IT";
            }
            if(jobBox == 1){
                job = "Junior IT";
            }
            if(jobBox == 2){
                job = "Senior IT";
            }
            if(jobBox == 3){
                job = "IT Manager";
            }
            float sal = Float.parseFloat(jTextField4.getText());
            int dept_id = Integer.parseInt(jTextField5.getText());
            java.math.BigInteger mng_id = BigInteger.valueOf(Long.parseLong(jTextField6.getText()));
            if( jTextField2.equals("") || jTextField3.equals("") || jTextField4.equals("") || jTextField5.equals("") || jTextField6.equals("")){
                showMessage("Khong duoc bo trong");
            } else if( sal <= 0 ||dept_id <=0 ){
                showMessage("Khong nhap so am");
            } else {
                
                emp = new Employee(id, name, no, hireDate, null, job, sal,dept_id, mng_id);
                jButton4.setEnabled(false);
                jButton1.setEnabled(true);
                labelID.setText("ID");
            }
        }catch(Exception e){
            showMessage("Nhap loi" + e);
        }
        return emp;
    }
    
    public int delEmployee(){
        int row = tblEmp.getSelectedRow();
        return Integer.parseInt(tblEmp.getModel().getValueAt(row, 0).toString());
    }
    
    
    //TIMEKEEPER
    public void showListTimekeeper(List<Timekeeper> list){
        int size = list.size();
        
        Object [][] tks = new Object[size][8];
        for(int i=0; i<size; i++){
            tks[i][0] = list.get(i).getTimekeeper_Id();
            tks[i][1] = list.get(i).getDate_Time();
            tks[i][2] = list.get(i).getIn_Out();
            tks[i][3] = list.get(i).getEmpId();
        }
        tblTK.setModel(new DefaultTableModel(tks, new String[] {"TK_ID", "DATE", "IN/OUT", "EMP_ID"}));
    }
    
    public Timekeeper getTimekeeper(){
        Timekeeper tk = null;
        try{    
            String id = null;
            switch(cbEmpID.getSelectedIndex()){
                case 0:
                    id = "TK1";
                    break;
                case 1:
                    id = "TK2";
                    break;
                case 2:
                    id = "TK3";
                    break;
                case 3:
                    id = "TK4";
                    break;
                default:
                    break;
            }
            String no = jTextField3.getText();
          
            SimpleDateFormat formatter = new SimpleDateFormat("dd/mm/yyyy");
            Date hireDate = formatter.parse(jFormattedTextField1.getText());
            int jobBox = jComboBox1.getSelectedIndex();
            String job = null;
            if(jobBox == 0){
                job = "Fresher IT";
            }
            if(jobBox == 1){
                job = "Junior IT";
            }
            if(jobBox == 2){
                job = "Senior IT";
            }
            if(jobBox == 3){
                job = "IT Manager";
            }
            float sal = Float.parseFloat(jTextField4.getText());
            int emp_id = Integer.parseInt(jTextField5.getText());
            java.math.BigInteger mng_id = BigInteger.valueOf(Long.parseLong(jTextField6.getText()));
            if( jTextField2.equals("") || jTextField3.equals("") || jTextField4.equals("") || jTextField5.equals("") || jTextField6.equals("")){
                showMessage("Khong duoc bo trong");
            } else if( sal <= 0  ){
                showMessage("Khong nhap so am");
            } else {               
                tk = new Timekeeper(id, hireDate, null, emp_id);              
            }
        }catch(Exception e){
            showMessage("Nhap loi" + e);
        }
        return tk;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JComboBox<String> cbEmpID;
    private javax.swing.JComboBox<String> cbInout;
    private javax.swing.JComboBox<String> cbTKID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel labelID;
    private javax.swing.JTable tblEmp;
    private javax.swing.JTable tblTK;
    // End of variables declaration//GEN-END:variables

}
